<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- TODO refactor to remove jquery -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script>
      $(document).ready(function() {
        var es = new EventSource("distill/{{collection_id}}");
        es.onmessage = function(e) {
          $("#waiting").remove();
          $("#log").html($("#log").html() + "<p>" + e.data + "</p>");
        };
      })
    </script>
  <style type="text/css">
    @keyframes ldio-ulzg7zjleaf {
      0% { transform: translate(6px,40px) scale(0); }
      25% { transform: translate(6px,40px) scale(0); }
      50% { transform: translate(6px,40px) scale(1); }
      75% { transform: translate(40px,40px) scale(1); }
     100% { transform: translate(74px,40px) scale(1); }
    }
    @keyframes ldio-ulzg7zjleaf-r {
      0% { transform: translate(74px,40px) scale(1): }
    100% { transform: translate(74px,40px) scale(0); }
    }
    @keyframes ldio-ulzg7zjleaf-c {
       0% { background: #000000 }
      25% { background: #000000 }
      50% { background: #000000 }
      75% { background: #000000 }
     100% { background: #000000 }
    }
    .ldio-ulzg7zjleaf div {
      position: absolute;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      transform: translate(40px,40px) scale(1);
      background: #000000;
      animation: ldio-ulzg7zjleaf 2s infinite cubic-bezier(0,0.5,0.5,1);
    }
    .ldio-ulzg7zjleaf div:nth-child(1) {
      background: #000000;
      transform: translate(74px,40px) scale(1);
      animation: ldio-ulzg7zjleaf-r 0.5s infinite cubic-bezier(0,0.5,0.5,1), ldio-ulzg7zjleaf-c 2s infinite step-start;
    }.ldio-ulzg7zjleaf div:nth-child(2) {
      animation-delay: -0.5s;
      background: #000000;
    }.ldio-ulzg7zjleaf div:nth-child(3) {
      animation-delay: -1s;
      background: #000000;
    }.ldio-ulzg7zjleaf div:nth-child(4) {
      animation-delay: -1.5s;
      background: #000000;
    }.ldio-ulzg7zjleaf div:nth-child(5) {
      animation-delay: -2s;
      background: #000000;
    }
    .loadingio-spinner-ellipsis-uhd4c3dmo6 {
      width: 32px;
      height: 32px;
      display: inline-block;
      overflow: hidden;
      background: none;
    }
    .ldio-ulzg7zjleaf {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(0.32);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-ulzg7zjleaf div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
  </style>
  </head>
  <body>
    <div id="log" style="font-family: monospace;">
      <div id="waiting" style="line-height: 32px;">
        <div style="display: inline-block; vertical-align: middle;">starting process for {{collection_id}}</em>, please wait (up to a minute)</div>
        <div class="loadingio-spinner-ellipsis-uhd4c3dmo6" style="vertical-align: middle;"><div class="ldio-ulzg7zjleaf"><div></div><div></div><div></div><div></div><div></div></div></div>
      </div>
    </div>
    <p><a href="/">return to form</a></p>
  </body>
</html>
